# Site settings
title: thirty-four
email: blog@posnick.org
description: "thirty-four is crafted with love in Brooklyn, by Jeff Posnick."
baseurl: ""
url: "https://jeffy.info"
github:
  username:  jeffposnick
twitter:
  username: jeffposnick
logo: /assets/images/34.png

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
exclude: ["firebase-debug.log", "firebase.json", "package-lock.json", "yarn.lock", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "package.json", "README.md", "src", "gulpfile.js"]
